name: My Workflow

on:
  push:
    tags:
      - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check if branch is main
      if: github.ref == 'refs/heads/dev'
      run: echo "The branch is dev"
      
    - name: Check if branch is not main
      if: github.ref != 'refs/heads/main'
      run: echo "The branch is not dev"
