name: My Workflow

on:
  push:
    tags:
      - '*'

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to dev
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: |
        # Add steps to deploy to dev environment
        
    - name: Deploy to qa
      if: ${{ github.ref == 'refs/heads/qa' }}
      run: |
        # Add steps to deploy to qa environment
        
    - name: Deploy to uat
      if: ${{ github.ref == 'refs/heads/uat' }}
      run: |
        # Add steps to deploy to uat environment
        
    - name: Deploy to prod
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        # Add steps to deploy to prod environment
